version: '2'
services:
  nginx:
    restart: always
    image: nginx:stable-alpine
    ports:
      - "80:80"
    links:
      - phpfpm:phpfpm
    volumes:
      - ./config/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx
      - ./cache/nginx:/var/cache/nginx
      - ./www:/usr/share/nginx/html
  phpfpm:
    restart: always
    build: ./php-fpm-7
    links:
      - db:dockerdb
    volumes:
      - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./config/php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./log/php-fpm:/var/log/php-fpm
      - ./www:/usr/share/nginx/html
  db:
    restart: always
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: databasewp
    volumes:
      - ./mysql/databases:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
  redis:
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:alpine
    ports:
      - "9300:9200"
  kibana:
    image: kibana
    ports:
     - "5601:5601"
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "6969:80"